services:
  app:
    container_name: api-tablu-tasks-app
    build:
      context: .
      target: ${NODE_ENV}
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      PORT: ${PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - api-tablu-tasks
    volumes:
      - .:/node/app
      - /node/app/node_modules

  mysql:
    image: mysql:latest
    restart: always
    container_name: api-tablu-tasks-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - api-tablu-tasks

  rabbitmq:
    image: rabbitmq:4.0.9-alpine
    container_name: api-tablu-tasks-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - api-tablu-tasks

volumes:
  mysql-data:

networks:
  api-tablu-tasks:
