version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-tablu-tasks
    container_name: api-tablu-tasks
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${NODE_PORT}
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    depends_on:
      - db
    networks:
      - api-tablu-tasks-network

  db:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-tablu-tasks-network

networks:
  api-tablu-tasks-network:
    driver: bridge

volumes:
  db_data:
